package dev.orestegabo.sequo.feature.settings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import org.jetbrains.compose.resources.StringResource
import sequo.shared.generated.resources.*

val LocalAppLanguage = compositionLocalOf { AppLanguage.English }

@Composable
fun appText(resource: StringResource): String =
    appText(resource, LocalAppLanguage.current)

fun appText(resource: StringResource, language: AppLanguage): String {
    val key = resource.key
    return when (language) {
        AppLanguage.English -> EnglishStrings[key]
        AppLanguage.French -> FrenchStrings[key]
    } ?: error("Missing ${language.name} translation for '$key'")
}

@Composable
fun appCatalogText(text: String): String =
    appCatalogText(text, LocalAppLanguage.current)

fun appCatalogText(text: String, language: AppLanguage): String {
    if (text.isBlank() || language == AppLanguage.English) return text
    return FrenchCatalogStrings[text.trim().lowercase()] ?: text
}

private val EnglishStrings = mapOf(
    Res.string.auth_sign_in_with.key to "Sign in with",
    Res.string.auth_continue_guest.key to "Continue as a guest",
    Res.string.auth_terms_prefix.key to "By continuing you accept",
    Res.string.auth_privacy_terms.key to "Privacy & Terms",
    Res.string.auth_more_options.key to "More sign-in options",
    Res.string.auth_last_used.key to "Last",
    Res.string.auth_signing_in.key to "Signing in...",
    Res.string.auth_continue_google.key to "Continue with Google",
    Res.string.auth_dialog_title.key to "Sign in",
    Res.string.common_ok.key to "OK",
    Res.string.onboarding_save_time_title.key to "Save time shopping",
    Res.string.onboarding_save_time_subtitle.key to "Browse nearby sellers, compare items, and build your basket without running across town.",
    Res.string.onboarding_riders_title.key to "Riders keep it moving",
    Res.string.onboarding_riders_subtitle.key to "Sequo riders handle pickup and delivery so your order gets from seller to you efficiently.",
    Res.string.onboarding_relay_title.key to "Pick up at relay points",
    Res.string.onboarding_relay_subtitle.key to "Send packages to a Sequo relay point when pickup nearby is easier than waiting at home.",
    Res.string.onboarding_deals_title.key to "Catch better deals",
    Res.string.onboarding_deals_subtitle.key to "Spot products on sale, save favorites, and come back when the right price shows up.",
    Res.string.nav_home_title.key to "Tokoin Gbadago",
    Res.string.nav_home_subtitle.key to "Deliver to Pharmacie des Etoiles area",
    Res.string.nav_markets_title.key to "Markets",
    Res.string.nav_markets_subtitle.key to "Verified Lome sellers",
    Res.string.nav_basket_title.key to "Cart",
    Res.string.nav_basket_subtitle.key to "Review and checkout",
    Res.string.nav_orders_title.key to "Orders",
    Res.string.nav_orders_subtitle.key to "Track every handoff",
    Res.string.nav_notifications_title.key to "Notifications",
    Res.string.nav_notifications_subtitle.key to "What needs your attention",
    Res.string.nav_account_title.key to "Account",
    Res.string.nav_account_subtitle.key to "Addresses, payment, and support",
    Res.string.bottom_home.key to "Sequo",
    Res.string.cd_back.key to "Back",
    Res.string.cd_open_menu.key to "Open menu",
    Res.string.cd_search.key to "Search",
    Res.string.cd_notifications.key to "Notifications",
    Res.string.guest_basket_title.key to "Sign in to build your basket",
    Res.string.guest_basket_detail.key to "You can inspect products and menus first. Saving cart items, choosing an address, and checkout require an account.",
    Res.string.guest_orders_title.key to "Sign in to track orders",
    Res.string.guest_orders_detail.key to "You can browse products as a guest. Orders, delivery status, pickup codes, returns, and receipts stay behind your account.",
    Res.string.common_browse.key to "Browse",
    Res.string.drawer_customer.key to "Sequo customer",
    Res.string.drawer_guest.key to "Guest browsing",
    Res.string.drawer_signed_in.key to "Signed in",
    Res.string.drawer_shop_categories.key to "Shop categories",
    Res.string.drawer_catalog_loading.key to "Catalog loading",
    Res.string.drawer_now.key to "Now",
    Res.string.drawer_marketplace_tools.key to "Marketplace tools",
    Res.string.drawer_promos.key to "Promos & campaigns",
    Res.string.drawer_promos_detail.key to "Lunch, holidays, weekend deals",
    Res.string.drawer_saved_shops.key to "Saved shops",
    Res.string.drawer_saved_shops_detail.key to "Favorite sellers and repeat buys",
    Res.string.drawer_delivery_areas.key to "Delivery areas",
    Res.string.drawer_delivery_areas_detail.key to "Lome zones and fees",
    Res.string.drawer_support.key to "Support",
    Res.string.drawer_support_detail.key to "Orders, refunds, seller help",
    Res.string.home_search_placeholder.key to "Search products or shops",
    Res.string.home_close_search.key to "Close search",
    Res.string.home_add.key to "Add",
    Res.string.home_view.key to "View",
    Res.string.home_make_offer.key to "Make an offer",
    Res.string.home_see_all.key to "See all",
    Res.string.home_less.key to "Less",
    Res.string.home_categories.key to "Categories",
    Res.string.home_popular_picks.key to "Popular picks",
    Res.string.home_nearby_shops.key to "Nearby shops",
    Res.string.home_catalog_load_error.key to "Unable to load Sequo catalog.",
    Res.string.home_unpin_category.key to "Unpin category",
    Res.string.home_pin_category.key to "Pin category",
    Res.string.home_pinned_max.key to "3 pinned max",
    Res.string.home_today_route.key to "Today route",
    Res.string.home_fees_visible.key to "fees visible",
    Res.string.home_nearby_fee.key to "400 CFA nearby",
    Res.string.home_product_view.key to "Product view",
    Res.string.home_relay_72h.key to "72h relay",
    Res.string.notif_filter_today.key to "Today",
    Res.string.notif_filter_attention.key to "Attention",
    Res.string.notif_filter_promos.key to "Promos",
    Res.string.notif_filter_archived.key to "Archived",
    Res.string.notif_header_attention.key to "Needs attention",
    Res.string.notif_inbox.key to "Inbox",
    Res.string.notif_unread.key to "unread",
    Res.string.notif_need_attention.key to "need attention",
    Res.string.notif_archived_lower.key to "archived",
    Res.string.notif_empty_detail.key to "All your notifications will be saved here for you to access their state anytime.",
    Res.string.notif_empty_today.key to "No notifications yet",
    Res.string.notif_empty_attention.key to "No urgent notifications",
    Res.string.notif_empty_promos.key to "No promos yet",
    Res.string.notif_empty_archived.key to "Nothing archived",
    Res.string.notif_cancelled_suffix.key to "cancelled",
    Res.string.notif_cancelled_detail.key to "The seller offer was refused and removed from checkout.",
    Res.string.notif_restore.key to "Restore",
    Res.string.notif_show.key to "Show",
    Res.string.notif_archive.key to "Archive",
    Res.string.notif_pickup_code.key to "Pickup code",
    Res.string.notif_handoff_hint.key to "Show this only at handoff.",
    Res.string.account_subscription_active.key to "Subscription active",
    Res.string.account_subscription_detail.key to "15% off / 500 CFA credit",
    Res.string.account_saved_places.key to "Saved places",
    Res.string.account_home.key to "Home",
    Res.string.account_family.key to "Family",
    Res.string.account_office.key to "Office",
    Res.string.account_supported_payments.key to "Supported payments",
    Res.string.account_no_cash.key to "no cash",
    Res.string.account_primary.key to "Primary",
    Res.string.account_backup.key to "Backup",
    Res.string.account_tools.key to "Account tools",
    Res.string.account_secure.key to "secure",
    Res.string.account_payments.key to "Payments",
    Res.string.account_returns.key to "Returns",
    Res.string.account_delivery_credit.key to "Delivery credit",
    Res.string.account_subscription.key to "Subscription",
    Res.string.account_active_15.key to "15% active",
    Res.string.account_guest_title.key to "Guest browsing",
    Res.string.account_guest_detail.key to "Create an account or sign in when you are ready to save baskets, place orders, track delivery, and manage payments.",
    Res.string.account_sign_in_create.key to "Sign in or create account",
    Res.string.account_customer.key to "Sequo customer",
    Res.string.account_no_email.key to "No email loaded",
    Res.string.account_provider.key to "Provider",
    Res.string.account_unknown.key to "unknown",
    Res.string.account_sign_out.key to "Sign out",
)

private val FrenchStrings = mapOf(
    Res.string.auth_sign_in_with.key to "Connectez-vous avec",
    Res.string.auth_continue_guest.key to "Continuer en invite",
    Res.string.auth_terms_prefix.key to "Vous acceptez",
    Res.string.auth_privacy_terms.key to "Confidentialite & conditions",
    Res.string.auth_more_options.key to "Autres options",
    Res.string.auth_last_used.key to "Dernier",
    Res.string.auth_signing_in.key to "Connexion...",
    Res.string.auth_continue_google.key to "Continuer avec Google",
    Res.string.auth_dialog_title.key to "Connexion",
    Res.string.common_ok.key to "OK",
    Res.string.onboarding_save_time_title.key to "Gagnez du temps",
    Res.string.onboarding_save_time_subtitle.key to "Parcourez les vendeurs proches, comparez les articles et preparez votre panier sans traverser la ville.",
    Res.string.onboarding_riders_title.key to "Les livreurs avancent",
    Res.string.onboarding_riders_subtitle.key to "Les livreurs Sequo gerent le retrait et la livraison pour que votre commande arrive efficacement.",
    Res.string.onboarding_relay_title.key to "Retrait en point relais",
    Res.string.onboarding_relay_subtitle.key to "Envoyez vos colis vers un point relais Sequo quand un retrait proche est plus simple que l'attente a domicile.",
    Res.string.onboarding_deals_title.key to "Trouvez de meilleures offres",
    Res.string.onboarding_deals_subtitle.key to "Reperez les produits en promo, gardez vos favoris et revenez quand le bon prix apparait.",
    Res.string.nav_home_title.key to "Tokoin Gbadago",
    Res.string.nav_home_subtitle.key to "Livraison Pharmacie des Etoiles",
    Res.string.nav_markets_title.key to "Marches",
    Res.string.nav_markets_subtitle.key to "Vendeurs verifies a Lome",
    Res.string.nav_basket_title.key to "Panier",
    Res.string.nav_basket_subtitle.key to "Verifier et payer",
    Res.string.nav_orders_title.key to "Commandes",
    Res.string.nav_orders_subtitle.key to "Suivi des etapes",
    Res.string.nav_notifications_title.key to "Notifications",
    Res.string.nav_notifications_subtitle.key to "A traiter",
    Res.string.nav_account_title.key to "Compte",
    Res.string.nav_account_subtitle.key to "Compte et support",
    Res.string.bottom_home.key to "Sequo",
    Res.string.cd_back.key to "Retour",
    Res.string.cd_open_menu.key to "Ouvrir le menu",
    Res.string.cd_search.key to "Rechercher",
    Res.string.cd_notifications.key to "Notifications",
    Res.string.guest_basket_title.key to "Connectez-vous pour creer votre panier",
    Res.string.guest_basket_detail.key to "Vous pouvez d'abord consulter les produits et les menus. Enregistrer le panier, choisir une adresse et payer demande un compte.",
    Res.string.guest_orders_title.key to "Connectez-vous pour suivre vos commandes",
    Res.string.guest_orders_detail.key to "Vous pouvez parcourir les produits en invite. Les commandes, statuts, codes de retrait, retours et recus restent dans votre compte.",
    Res.string.common_browse.key to "Parcourir",
    Res.string.drawer_customer.key to "Client Sequo",
    Res.string.drawer_guest.key to "Invite",
    Res.string.drawer_signed_in.key to "Connecte",
    Res.string.drawer_shop_categories.key to "Categories",
    Res.string.drawer_catalog_loading.key to "Chargement...",
    Res.string.drawer_now.key to "Actuel",
    Res.string.drawer_marketplace_tools.key to "Outils",
    Res.string.drawer_promos.key to "Promos",
    Res.string.drawer_promos_detail.key to "Midi, fetes, week-end",
    Res.string.drawer_saved_shops.key to "Favoris",
    Res.string.drawer_saved_shops_detail.key to "Vendeurs et rachats",
    Res.string.drawer_delivery_areas.key to "Livraison",
    Res.string.drawer_delivery_areas_detail.key to "Zones et frais",
    Res.string.drawer_support.key to "Support",
    Res.string.drawer_support_detail.key to "Aide commandes",
    Res.string.home_search_placeholder.key to "Produit ou boutique",
    Res.string.home_close_search.key to "Fermer",
    Res.string.home_add.key to "Ajouter",
    Res.string.home_view.key to "Voir",
    Res.string.home_make_offer.key to "Offrir",
    Res.string.home_see_all.key to "Voir tout",
    Res.string.home_less.key to "Moins",
    Res.string.home_categories.key to "Categories",
    Res.string.home_popular_picks.key to "Populaires",
    Res.string.home_nearby_shops.key to "Proches",
    Res.string.home_catalog_load_error.key to "Impossible de charger le catalogue Sequo.",
    Res.string.home_unpin_category.key to "Retirer",
    Res.string.home_pin_category.key to "Epingler",
    Res.string.home_pinned_max.key to "3 categories max",
    Res.string.home_today_route.key to "Trajet",
    Res.string.home_fees_visible.key to "frais",
    Res.string.home_nearby_fee.key to "400 CFA pres",
    Res.string.home_product_view.key to "Photo",
    Res.string.home_relay_72h.key to "Relais 72h",
    Res.string.notif_filter_today.key to "Auj.",
    Res.string.notif_filter_attention.key to "Attention",
    Res.string.notif_filter_promos.key to "Promos",
    Res.string.notif_filter_archived.key to "Archives",
    Res.string.notif_header_attention.key to "A traiter",
    Res.string.notif_inbox.key to "Inbox",
    Res.string.notif_unread.key to "non lus",
    Res.string.notif_need_attention.key to "a traiter",
    Res.string.notif_archived_lower.key to "archives",
    Res.string.notif_empty_detail.key to "Toutes vos notifications seront gardees ici pour consulter leur etat a tout moment.",
    Res.string.notif_empty_today.key to "Aucune notification",
    Res.string.notif_empty_attention.key to "Aucune urgence",
    Res.string.notif_empty_promos.key to "Aucune promo",
    Res.string.notif_empty_archived.key to "Rien d'archive",
    Res.string.notif_cancelled_suffix.key to "annulee",
    Res.string.notif_cancelled_detail.key to "L'offre du vendeur a ete refusee et retiree du paiement.",
    Res.string.notif_restore.key to "Restaurer",
    Res.string.notif_show.key to "Afficher",
    Res.string.notif_archive.key to "Archiver",
    Res.string.notif_pickup_code.key to "Code retrait",
    Res.string.notif_handoff_hint.key to "A montrer seulement lors de la remise.",
    Res.string.account_subscription_active.key to "Abonne",
    Res.string.account_subscription_detail.key to "-15% / 500 CFA credit",
    Res.string.account_saved_places.key to "Adresses",
    Res.string.account_home.key to "Maison",
    Res.string.account_family.key to "Famille",
    Res.string.account_office.key to "Bureau",
    Res.string.account_supported_payments.key to "Paiements",
    Res.string.account_no_cash.key to "sans cash",
    Res.string.account_primary.key to "Principal",
    Res.string.account_backup.key to "Secours",
    Res.string.account_tools.key to "Outils",
    Res.string.account_secure.key to "securise",
    Res.string.account_payments.key to "Paiements",
    Res.string.account_returns.key to "Retours",
    Res.string.account_delivery_credit.key to "Credit livr.",
    Res.string.account_subscription.key to "Abonnement",
    Res.string.account_active_15.key to "15% actif",
    Res.string.account_guest_title.key to "Invite",
    Res.string.account_guest_detail.key to "Creez un compte ou connectez-vous quand vous voulez enregistrer des paniers, commander, suivre la livraison et gerer les paiements.",
    Res.string.account_sign_in_create.key to "Connexion / compte",
    Res.string.account_customer.key to "Client Sequo",
    Res.string.account_no_email.key to "Aucun email",
    Res.string.account_provider.key to "Provider",
    Res.string.account_unknown.key to "inconnu",
    Res.string.account_sign_out.key to "Se deconnecter",
)

private val FrenchCatalogStrings = mapOf(
    "all" to "Tout",
    "catalog" to "Catalogue",
    "available" to "Disponible",
    "catalog synced" to "Catalogue synchronise",
    "standard delivery" to "Livraison standard",
    "negotiable" to "Negociable",
    "food" to "Repas",
    "grocery" to "Epicerie",
    "fashion" to "Mode",
    "electronics" to "Tech",
    "pharmacy" to "Pharmacie",
    "beauty" to "Beaute",
    "bargains" to "Deals",
    "hot meal" to "Chaud",
    "hot meals" to "Chaud",
    "meals" to "Repas",
    "meal" to "Repas",
    "fast food" to "Fast-food",
    "restaurant" to "Restaurant",
    "restaurants" to "Restaurants",
    "fresh food" to "Frais",
    "fresh" to "Frais",
    "daily" to "Quotidien",
    "market" to "Marche",
    "markets" to "Marches",
    "shops" to "Boutiques",
    "shop" to "Boutique",
    "store" to "Boutique",
    "stores" to "Boutiques",
    "baby care" to "Bebe",
    "soaps & cleaners" to "Savons et menage",
    "paper goods" to "Papier",
    "socks" to "Chaussettes",
    "football jerseys" to "Maillots",
    "basketball jerseys" to "Basket",
    "shoes" to "Chaussures",
    "t-shirts" to "T-shirts",
    "shirts" to "Chemises",
    "shorts" to "Shorts",
    "denim" to "Jean",
    "watches" to "Montres",
    "perfume" to "Parfum",
    "makeup" to "Maquillage",
    "phones" to "Telephones",
    "laptops" to "Ordinateurs",
    "auto parts" to "Auto",
    "seafood" to "Poisson",
    "meat" to "Viande",
    "pantry" to "Epicerie",
    "produce" to "Frais",
    "open" to "Ouvert",
    "closed" to "Ferme",
)
