package dev.orestegabo.sequo.feature.settings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import org.jetbrains.compose.resources.StringResource
import sequo.shared.generated.resources.*

val LocalAppLanguage = compositionLocalOf { AppLanguage.English }

@Composable
fun appText(resource: StringResource): String =
    appText(resource, LocalAppLanguage.current)

fun appText(resource: StringResource, language: AppLanguage): String {
    val key = resource.key
    return when (language) {
        AppLanguage.English -> EnglishStrings[key]
        AppLanguage.French -> FrenchStrings[key]
    } ?: error("Missing ${language.name} translation for '$key'")
}

@Composable
fun appCatalogText(text: String): String =
    appCatalogText(text, LocalAppLanguage.current)

fun appCatalogText(text: String, language: AppLanguage): String {
    if (text.isBlank() || language == AppLanguage.English) return text
    return FrenchCatalogStrings[text.trim().lowercase()] ?: text
}

private val EnglishStrings = mapOf(
    Res.string.auth_sign_in_with.key to "Sign in with",
    Res.string.auth_continue_guest.key to "Continue as a guest",
    Res.string.auth_continue_as.key to "Continue as %1\$s",
    Res.string.auth_terms_prefix.key to "By continuing you accept",
    Res.string.auth_privacy_terms.key to "Privacy & Terms",
    Res.string.auth_more_options.key to "More sign-in options",
    Res.string.auth_last_used.key to "Last",
    Res.string.auth_signing_in.key to "Signing in...",
    Res.string.auth_continue_google.key to "Continue with Google",
    Res.string.auth_dialog_title.key to "Sign in",
    Res.string.auth_email_address.key to "Email address",
    Res.string.auth_email_sign_in.key to "Email sign-in",
    Res.string.auth_email_sign_up.key to "Email sign-up",
    Res.string.auth_full_name.key to "Full name",
    Res.string.auth_birth_date.key to "Birth date",
    Res.string.auth_birth_date_placeholder.key to "DD/MM/YYYY",
    Res.string.common_ok.key to "OK",
    Res.string.common_cancel.key to "Cancel",
    Res.string.auth_error_sign_in_again.key to "Please sign in again to continue.",
    Res.string.auth_error_email_sign_in_failed.key to "Email sign-in could not be completed. Please try again.",
    Res.string.auth_error_account_creation_failed.key to "Account creation could not be completed. Please try again.",
    Res.string.auth_error_email_format.key to "Check the email and password format.",
    Res.string.auth_error_email_password.key to "Email or password is incorrect.",
    Res.string.auth_error_account_other_method.key to "This account must be opened with another sign-in method.",
    Res.string.auth_error_too_many_attempts.key to "Too many attempts. Please wait before trying again.",
    Res.string.auth_error_unavailable.key to "Authentication is temporarily unavailable. Please try again later.",
    Res.string.auth_error_social_failed.key to "Sign-in could not be completed. Please try again.",
    Res.string.auth_error_social_unavailable.key to "This sign-in option is temporarily unavailable. Please try again later.",
    Res.string.auth_error_google_failed.key to "Google sign-in could not be completed. Please try again.",
    Res.string.auth_error_google_interrupted.key to "Google sign-in was cancelled or interrupted. Please try again.",
    Res.string.auth_error_google_in_progress.key to "Google sign-in is already running.",
    Res.string.auth_error_google_not_configured.key to "Google sign-in is temporarily unavailable. Please use another sign-in option or try again later.",
    Res.string.auth_error_google_unavailable.key to "Google sign-in is temporarily unavailable. Please try again later.",
    Res.string.auth_error_google_expired.key to "Google returned an expired sign-in token. Please try again.",
    Res.string.auth_error_google_missing_email.key to "Google did not share an email address for this account.",
    Res.string.auth_error_google_unverified_email.key to "Google says this account email is not verified.",
    Res.string.auth_error_google_could_not_verify.key to "Google sign-in could not be verified. Please try again.",
    Res.string.auth_error_profile_load_failed.key to "Could not load the authenticated user profile.",
    Res.string.auth_error_session_restore_failed.key to "Could not restore the saved session.",
    Res.string.auth_error_biometric_unavailable.key to "Biometric unlock is not available on this device. Sign in again to continue.",
    Res.string.auth_error_biometric_failed.key to "Biometric unlock failed. Sign in again to continue.",
    Res.string.auth_error_apple_not_ready.key to "Apple sign-in is not ready yet.",
    Res.string.auth_error_facebook_not_ready.key to "Facebook sign-in is not ready yet.",
    Res.string.auth_error_whatsapp_not_ready.key to "WhatsApp sign-in is not ready yet.",
    Res.string.auth_error_passkey_not_ready.key to "Passkey sign-in is not ready yet.",
    Res.string.auth_error_sequo_login_not_ready.key to "Login by Sequo is not ready yet.",
    Res.string.biometric_prompt_title.key to "Unlock Sequo",
    Res.string.biometric_prompt_subtitle.key to "Use biometrics to restore your saved session.",
    Res.string.api_health_unreachable.key to "Unable to reach Sequo service. Please check your connection and try again.",
    Res.string.onboarding_save_time_title.key to "Save time shopping",
    Res.string.onboarding_save_time_subtitle.key to "Browse nearby sellers, compare items, and build your basket without running across town.",
    Res.string.onboarding_riders_title.key to "Riders keep it moving",
    Res.string.onboarding_riders_subtitle.key to "Sequo riders handle pickup and delivery so your order gets from seller to you efficiently.",
    Res.string.onboarding_relay_title.key to "Pick up at relay points",
    Res.string.onboarding_relay_subtitle.key to "Send packages to a Sequo relay point when pickup nearby is easier than waiting at home.",
    Res.string.onboarding_deals_title.key to "Catch better deals",
    Res.string.onboarding_deals_subtitle.key to "Spot products on sale, save favorites, and come back when the right price shows up.",
    Res.string.nav_home_title.key to "Tokoin Gbadago",
    Res.string.nav_home_subtitle.key to "Deliver to Pharmacie des Etoiles area",
    Res.string.nav_markets_title.key to "Markets",
    Res.string.nav_markets_subtitle.key to "Verified Lome sellers",
    Res.string.nav_basket_title.key to "Cart",
    Res.string.nav_basket_subtitle.key to "Review and checkout",
    Res.string.nav_orders_title.key to "Orders",
    Res.string.nav_orders_subtitle.key to "Track every handoff",
    Res.string.nav_notifications_title.key to "Notifications",
    Res.string.nav_notifications_subtitle.key to "What needs your attention",
    Res.string.nav_account_title.key to "Account",
    Res.string.nav_account_subtitle.key to "Addresses, payment, and support",
    Res.string.bottom_home.key to "Sequo",
    Res.string.cd_back.key to "Back",
    Res.string.cd_open_menu.key to "Open menu",
    Res.string.cd_search.key to "Search",
    Res.string.cd_notifications.key to "Notifications",
    Res.string.guest_basket_title.key to "Sign in to build your basket",
    Res.string.guest_basket_detail.key to "You can inspect products and menus first. Saving cart items, choosing an address, and checkout require an account.",
    Res.string.guest_orders_title.key to "Sign in to track orders",
    Res.string.guest_orders_detail.key to "You can browse products as a guest. Orders, delivery status, pickup codes, returns, and receipts stay behind your account.",
    Res.string.common_browse.key to "Browse",
    Res.string.drawer_customer.key to "Sequo customer",
    Res.string.drawer_guest.key to "Guest browsing",
    Res.string.drawer_signed_in.key to "Signed in",
    Res.string.drawer_quick_links.key to "Fast links",
    Res.string.drawer_orders.key to "Orders",
    Res.string.drawer_cart.key to "Cart",
    Res.string.drawer_alerts.key to "Alerts",
    Res.string.drawer_profile.key to "Profile",
    Res.string.drawer_settings.key to "Settings",
    Res.string.drawer_language.key to "Language",
    Res.string.drawer_language_en.key to "EN",
    Res.string.drawer_language_fr.key to "FR",
    Res.string.drawer_theme.key to "Theme",
    Res.string.drawer_theme_system.key to "Auto",
    Res.string.drawer_theme_light.key to "Light",
    Res.string.drawer_theme_dark.key to "Dark",
    Res.string.drawer_shop_categories.key to "Shop categories",
    Res.string.drawer_catalog_loading.key to "Catalog loading",
    Res.string.drawer_now.key to "Now",
    Res.string.drawer_marketplace_tools.key to "Marketplace tools",
    Res.string.drawer_promos.key to "Promos & campaigns",
    Res.string.drawer_promos_detail.key to "Lunch, holidays, weekend deals",
    Res.string.drawer_saved_shops.key to "Saved shops",
    Res.string.drawer_saved_shops_detail.key to "Favorite sellers and repeat buys",
    Res.string.drawer_delivery_areas.key to "Delivery areas",
    Res.string.drawer_delivery_areas_detail.key to "Lome zones and fees",
    Res.string.drawer_support.key to "Support",
    Res.string.drawer_support_detail.key to "Orders, refunds, seller help",
    Res.string.home_search_placeholder.key to "Search products or shops",
    Res.string.home_close_search.key to "Close search",
    Res.string.home_add.key to "Add",
    Res.string.home_view.key to "View",
    Res.string.home_make_offer.key to "Make an offer",
    Res.string.home_see_all.key to "See all",
    Res.string.home_less.key to "Less",
    Res.string.home_categories.key to "Categories",
    Res.string.home_popular_picks.key to "Popular picks",
    Res.string.home_nearby_shops.key to "Nearby shops",
    Res.string.home_catalog_load_error.key to "Unable to load Sequo catalog.",
    Res.string.home_unpin_category.key to "Unpin category",
    Res.string.home_pin_category.key to "Pin category",
    Res.string.home_pinned_max.key to "3 pinned max",
    Res.string.home_today_route.key to "Today route",
    Res.string.home_fees_visible.key to "fees visible",
    Res.string.home_nearby_fee.key to "400 CFA nearby",
    Res.string.home_product_view.key to "Product view",
    Res.string.home_relay_72h.key to "72h relay",
    Res.string.photo_action_post_pending.key to "Posting photos will connect to seller tools next.",
    Res.string.photo_action_copy_pending.key to "Image copy needs native clipboard support next.",
    Res.string.photo_action_saving.key to "Saving watermarked photo...",
    Res.string.photo_action_edit_pending.key to "Photo editing will open from this menu next.",
    Res.string.photo_action_preparing_share.key to "Preparing watermarked share...",
    Res.string.photo_export_save_failed.key to "Could not save the photo. Please check storage access and try again.",
    Res.string.photo_export_saved.key to "Saved with Sequo watermark.",
    Res.string.photo_export_prepare_failed.key to "Could not prepare the photo.",
    Res.string.photo_export_opening_share.key to "Opening share options.",
    Res.string.photo_export_share_failed.key to "Could not share the photo. Please try again.",
    Res.string.photo_export_ios_save_pending.key to "Photo saving is not ready on iOS yet.",
    Res.string.photo_export_ios_share_pending.key to "Photo sharing is not ready on iOS yet.",
    Res.string.legal_pdf_create_failed.key to "Could not create the PDF file.",
    Res.string.legal_pdf_open_failed.key to "Could not open the PDF file.",
    Res.string.legal_pdf_save_failed.key to "Could not save the PDF. Please check storage access and try again.",
    Res.string.legal_pdf_saved.key to "Saved to Downloads.",
    Res.string.legal_pdf_share_sheet_failed.key to "Could not open the iOS share sheet.",
    Res.string.legal_pdf_share_sheet_ready.key to "Choose Files, Messages, WhatsApp, Mail, AirDrop, or another app.",
    Res.string.legal_pdf_prepare_failed.key to "Could not prepare the PDF. Please try again.",
    Res.string.legal_download_pdf.key to "Download PDF",
    Res.string.basket_added_browsing.key to "Added while browsing",
    Res.string.basket_temporary_item.key to "Temporary basket item",
    Res.string.basket_delivery_packaging.key to "Delivery & packaging",
    Res.string.basket_packages_detail.key to "%1\$d packages with item and delivery details",
    Res.string.basket_delivery.key to "Delivery",
    Res.string.basket_collapse_delivery_fees.key to "Collapse delivery fees",
    Res.string.basket_show_delivery_fees.key to "Show delivery fees",
    Res.string.basket_package_label.key to "Package %1\$s",
    Res.string.orders_returns_current_title.key to "Returns stay current for 72 hours",
    Res.string.orders_returns_current_detail.key to "Eligible delivered orders remain here until the return window closes.",
    Res.string.orders_back_to_orders.key to "Back to orders",
    Res.string.orders_detail_title.key to "Order detail",
    Res.string.orders_seller_pickup_code.key to "Seller pickup code",
    Res.string.pass_access_title.key to "SEQUO ACCESS",
    Res.string.pass_subscriber_detail.key to "Lome subscriber / 15% delivery discount",
    Res.string.pass_credit.key to "500 CFA credit",
    Res.string.pass_addresses.key to "3 Lome addresses",
    Res.string.notif_filter_today.key to "Today",
    Res.string.notif_filter_attention.key to "Attention",
    Res.string.notif_filter_promos.key to "Promos",
    Res.string.notif_filter_archived.key to "Archived",
    Res.string.notif_header_attention.key to "Needs attention",
    Res.string.notif_inbox.key to "Inbox",
    Res.string.notif_unread.key to "unread",
    Res.string.notif_need_attention.key to "need attention",
    Res.string.notif_archived_lower.key to "archived",
    Res.string.notif_empty_detail.key to "All your notifications will be saved here for you to access their state anytime.",
    Res.string.notif_empty_today.key to "No notifications yet",
    Res.string.notif_empty_attention.key to "No urgent notifications",
    Res.string.notif_empty_promos.key to "No promos yet",
    Res.string.notif_empty_archived.key to "Nothing archived",
    Res.string.notif_cancelled_suffix.key to "cancelled",
    Res.string.notif_cancelled_detail.key to "The seller offer was refused and removed from checkout.",
    Res.string.notif_restore.key to "Restore",
    Res.string.notif_show.key to "Show",
    Res.string.notif_archive.key to "Archive",
    Res.string.notif_pickup_code.key to "Pickup code",
    Res.string.notif_handoff_hint.key to "Show this only at handoff.",
    Res.string.account_subscription_active.key to "Subscription active",
    Res.string.account_subscription_detail.key to "15% off / 500 CFA credit",
    Res.string.account_saved_places.key to "Saved places",
    Res.string.account_home.key to "Home",
    Res.string.account_family.key to "Family",
    Res.string.account_office.key to "Office",
    Res.string.account_supported_payments.key to "Supported payments",
    Res.string.account_no_cash.key to "no cash",
    Res.string.account_primary.key to "Primary",
    Res.string.account_backup.key to "Backup",
    Res.string.account_tools.key to "Account tools",
    Res.string.account_secure.key to "secure",
    Res.string.account_payments.key to "Payments",
    Res.string.account_returns.key to "Returns",
    Res.string.account_delivery_credit.key to "Delivery credit",
    Res.string.account_subscription.key to "Subscription",
    Res.string.account_active_15.key to "15% active",
    Res.string.account_guest_title.key to "Guest browsing",
    Res.string.account_guest_detail.key to "Create an account or sign in when you are ready to save baskets, place orders, track delivery, and manage payments.",
    Res.string.account_sign_in_create.key to "Sign in or create account",
    Res.string.account_customer.key to "Sequo customer",
    Res.string.account_no_email.key to "No email loaded",
    Res.string.account_provider.key to "Provider",
    Res.string.account_unknown.key to "unknown",
    Res.string.account_sign_out.key to "Sign out",
)

private val FrenchStrings = mapOf(
    Res.string.auth_sign_in_with.key to "Connectez-vous avec",
    Res.string.auth_continue_guest.key to "Continuer en invite",
    Res.string.auth_continue_as.key to "Continuer avec %1\$s",
    Res.string.auth_terms_prefix.key to "Vous acceptez",
    Res.string.auth_privacy_terms.key to "Confidentialite & conditions",
    Res.string.auth_more_options.key to "Autres options",
    Res.string.auth_last_used.key to "Dernier",
    Res.string.auth_signing_in.key to "Connexion...",
    Res.string.auth_continue_google.key to "Continuer avec Google",
    Res.string.auth_dialog_title.key to "Connexion",
    Res.string.auth_email_address.key to "Adresse email",
    Res.string.auth_email_sign_in.key to "Connexion email",
    Res.string.auth_email_sign_up.key to "Inscription email",
    Res.string.auth_full_name.key to "Nom complet",
    Res.string.auth_birth_date.key to "Date de naissance",
    Res.string.auth_birth_date_placeholder.key to "JJ/MM/AAAA",
    Res.string.common_ok.key to "OK",
    Res.string.common_cancel.key to "Annuler",
    Res.string.auth_error_sign_in_again.key to "Veuillez vous reconnecter pour continuer.",
    Res.string.auth_error_email_sign_in_failed.key to "La connexion par email a echoue. Reessayez.",
    Res.string.auth_error_account_creation_failed.key to "La creation du compte a echoue. Reessayez.",
    Res.string.auth_error_email_format.key to "Verifiez le format de l'email et du mot de passe.",
    Res.string.auth_error_email_password.key to "Email ou mot de passe incorrect.",
    Res.string.auth_error_account_other_method.key to "Ce compte doit etre ouvert avec une autre methode de connexion.",
    Res.string.auth_error_too_many_attempts.key to "Trop de tentatives. Patientez avant de reessayer.",
    Res.string.auth_error_unavailable.key to "La connexion est temporairement indisponible. Reessayez plus tard.",
    Res.string.auth_error_social_failed.key to "La connexion a echoue. Reessayez.",
    Res.string.auth_error_social_unavailable.key to "Cette option de connexion est temporairement indisponible. Reessayez plus tard.",
    Res.string.auth_error_google_failed.key to "La connexion Google a echoue. Reessayez.",
    Res.string.auth_error_google_interrupted.key to "La connexion Google a ete annulee ou interrompue. Reessayez.",
    Res.string.auth_error_google_in_progress.key to "La connexion Google est deja en cours.",
    Res.string.auth_error_google_not_configured.key to "La connexion Google est temporairement indisponible. Utilisez une autre option ou reessayez plus tard.",
    Res.string.auth_error_google_unavailable.key to "La connexion Google est temporairement indisponible. Reessayez plus tard.",
    Res.string.auth_error_google_expired.key to "La session Google a expire. Reessayez.",
    Res.string.auth_error_google_missing_email.key to "Google n'a pas partage d'adresse email pour ce compte.",
    Res.string.auth_error_google_unverified_email.key to "Google indique que l'email de ce compte n'est pas verifie.",
    Res.string.auth_error_google_could_not_verify.key to "La connexion Google n'a pas pu etre verifiee. Reessayez.",
    Res.string.auth_error_profile_load_failed.key to "Impossible de charger le profil connecte.",
    Res.string.auth_error_session_restore_failed.key to "Impossible de restaurer la session enregistree.",
    Res.string.auth_error_biometric_unavailable.key to "Le deverrouillage biometrique n'est pas disponible sur cet appareil. Reconnectez-vous pour continuer.",
    Res.string.auth_error_biometric_failed.key to "Le deverrouillage biometrique a echoue. Reconnectez-vous pour continuer.",
    Res.string.auth_error_apple_not_ready.key to "La connexion Apple n'est pas encore prete.",
    Res.string.auth_error_facebook_not_ready.key to "La connexion Facebook n'est pas encore prete.",
    Res.string.auth_error_whatsapp_not_ready.key to "La connexion WhatsApp n'est pas encore prete.",
    Res.string.auth_error_passkey_not_ready.key to "La connexion par passkey n'est pas encore prete.",
    Res.string.auth_error_sequo_login_not_ready.key to "La connexion par Sequo n'est pas encore prete.",
    Res.string.biometric_prompt_title.key to "Deverrouiller Sequo",
    Res.string.biometric_prompt_subtitle.key to "Utilisez la biometrie pour restaurer votre session.",
    Res.string.api_health_unreachable.key to "Impossible de joindre le service Sequo. Verifiez votre connexion et reessayez.",
    Res.string.onboarding_save_time_title.key to "Gagnez du temps",
    Res.string.onboarding_save_time_subtitle.key to "Parcourez les vendeurs proches, comparez les articles et preparez votre panier sans traverser la ville.",
    Res.string.onboarding_riders_title.key to "Les livreurs avancent",
    Res.string.onboarding_riders_subtitle.key to "Les livreurs Sequo gerent le retrait et la livraison pour que votre commande arrive efficacement.",
    Res.string.onboarding_relay_title.key to "Retrait en point relais",
    Res.string.onboarding_relay_subtitle.key to "Envoyez vos colis vers un point relais Sequo quand un retrait proche est plus simple que l'attente a domicile.",
    Res.string.onboarding_deals_title.key to "Trouvez de meilleures offres",
    Res.string.onboarding_deals_subtitle.key to "Reperez les produits en promo, gardez vos favoris et revenez quand le bon prix apparait.",
    Res.string.nav_home_title.key to "Tokoin Gbadago",
    Res.string.nav_home_subtitle.key to "Livraison Pharmacie des Etoiles",
    Res.string.nav_markets_title.key to "Marches",
    Res.string.nav_markets_subtitle.key to "Vendeurs verifies a Lome",
    Res.string.nav_basket_title.key to "Panier",
    Res.string.nav_basket_subtitle.key to "Verifier et payer",
    Res.string.nav_orders_title.key to "Commandes",
    Res.string.nav_orders_subtitle.key to "Suivi des etapes",
    Res.string.nav_notifications_title.key to "Notifications",
    Res.string.nav_notifications_subtitle.key to "A traiter",
    Res.string.nav_account_title.key to "Compte",
    Res.string.nav_account_subtitle.key to "Compte et support",
    Res.string.bottom_home.key to "Sequo",
    Res.string.cd_back.key to "Retour",
    Res.string.cd_open_menu.key to "Ouvrir le menu",
    Res.string.cd_search.key to "Rechercher",
    Res.string.cd_notifications.key to "Notifications",
    Res.string.guest_basket_title.key to "Connectez-vous pour creer votre panier",
    Res.string.guest_basket_detail.key to "Vous pouvez d'abord consulter les produits et les menus. Enregistrer le panier, choisir une adresse et payer demande un compte.",
    Res.string.guest_orders_title.key to "Connectez-vous pour suivre vos commandes",
    Res.string.guest_orders_detail.key to "Vous pouvez parcourir les produits en invite. Les commandes, statuts, codes de retrait, retours et recus restent dans votre compte.",
    Res.string.common_browse.key to "Parcourir",
    Res.string.drawer_customer.key to "Client Sequo",
    Res.string.drawer_guest.key to "Invite",
    Res.string.drawer_signed_in.key to "Connecte",
    Res.string.drawer_quick_links.key to "Acces rapides",
    Res.string.drawer_orders.key to "Commandes",
    Res.string.drawer_cart.key to "Panier",
    Res.string.drawer_alerts.key to "Alertes",
    Res.string.drawer_profile.key to "Profil",
    Res.string.drawer_settings.key to "Reglages",
    Res.string.drawer_language.key to "Langue",
    Res.string.drawer_language_en.key to "EN",
    Res.string.drawer_language_fr.key to "FR",
    Res.string.drawer_theme.key to "Theme",
    Res.string.drawer_theme_system.key to "Auto",
    Res.string.drawer_theme_light.key to "Clair",
    Res.string.drawer_theme_dark.key to "Sombre",
    Res.string.drawer_shop_categories.key to "Categories",
    Res.string.drawer_catalog_loading.key to "Chargement...",
    Res.string.drawer_now.key to "Actuel",
    Res.string.drawer_marketplace_tools.key to "Outils",
    Res.string.drawer_promos.key to "Promos",
    Res.string.drawer_promos_detail.key to "Midi, fetes, week-end",
    Res.string.drawer_saved_shops.key to "Favoris",
    Res.string.drawer_saved_shops_detail.key to "Vendeurs et rachats",
    Res.string.drawer_delivery_areas.key to "Livraison",
    Res.string.drawer_delivery_areas_detail.key to "Zones et frais",
    Res.string.drawer_support.key to "Support",
    Res.string.drawer_support_detail.key to "Aide commandes",
    Res.string.home_search_placeholder.key to "Produit ou boutique",
    Res.string.home_close_search.key to "Fermer",
    Res.string.home_add.key to "Ajouter",
    Res.string.home_view.key to "Voir",
    Res.string.home_make_offer.key to "Offrir",
    Res.string.home_see_all.key to "Voir tout",
    Res.string.home_less.key to "Moins",
    Res.string.home_categories.key to "Categories",
    Res.string.home_popular_picks.key to "Populaires",
    Res.string.home_nearby_shops.key to "Proches",
    Res.string.home_catalog_load_error.key to "Impossible de charger le catalogue Sequo.",
    Res.string.home_unpin_category.key to "Retirer",
    Res.string.home_pin_category.key to "Epingler",
    Res.string.home_pinned_max.key to "3 categories max",
    Res.string.home_today_route.key to "Trajet",
    Res.string.home_fees_visible.key to "frais",
    Res.string.home_nearby_fee.key to "400 CFA pres",
    Res.string.home_product_view.key to "Photo",
    Res.string.home_relay_72h.key to "Relais 72h",
    Res.string.photo_action_post_pending.key to "La publication des photos sera reliee aux outils vendeur ensuite.",
    Res.string.photo_action_copy_pending.key to "La copie d'image demandera ensuite le support presse-papiers natif.",
    Res.string.photo_action_saving.key to "Enregistrement de la photo avec filigrane...",
    Res.string.photo_action_edit_pending.key to "La retouche photo s'ouvrira depuis ce menu ensuite.",
    Res.string.photo_action_preparing_share.key to "Preparation du partage avec filigrane...",
    Res.string.photo_export_save_failed.key to "Impossible d'enregistrer la photo. Verifiez l'acces au stockage et reessayez.",
    Res.string.photo_export_saved.key to "Enregistre avec le filigrane Sequo.",
    Res.string.photo_export_prepare_failed.key to "Impossible de preparer la photo.",
    Res.string.photo_export_opening_share.key to "Ouverture des options de partage.",
    Res.string.photo_export_share_failed.key to "Impossible de partager la photo. Reessayez.",
    Res.string.photo_export_ios_save_pending.key to "L'enregistrement photo n'est pas encore pret sur iOS.",
    Res.string.photo_export_ios_share_pending.key to "Le partage photo n'est pas encore pret sur iOS.",
    Res.string.legal_pdf_create_failed.key to "Impossible de creer le fichier PDF.",
    Res.string.legal_pdf_open_failed.key to "Impossible d'ouvrir le fichier PDF.",
    Res.string.legal_pdf_save_failed.key to "Impossible d'enregistrer le PDF. Verifiez l'acces au stockage et reessayez.",
    Res.string.legal_pdf_saved.key to "Enregistre dans Telechargements.",
    Res.string.legal_pdf_share_sheet_failed.key to "Impossible d'ouvrir le partage iOS.",
    Res.string.legal_pdf_share_sheet_ready.key to "Choisissez Fichiers, Messages, WhatsApp, Mail, AirDrop ou une autre app.",
    Res.string.legal_pdf_prepare_failed.key to "Impossible de preparer le PDF. Reessayez.",
    Res.string.legal_download_pdf.key to "Telecharger le PDF",
    Res.string.basket_added_browsing.key to "Ajoute pendant la navigation",
    Res.string.basket_temporary_item.key to "Article temporaire du panier",
    Res.string.basket_delivery_packaging.key to "Livraison & emballage",
    Res.string.basket_packages_detail.key to "%1\$d colis avec details des articles et de livraison",
    Res.string.basket_delivery.key to "Livraison",
    Res.string.basket_collapse_delivery_fees.key to "Masquer les frais de livraison",
    Res.string.basket_show_delivery_fees.key to "Afficher les frais de livraison",
    Res.string.basket_package_label.key to "Colis %1\$s",
    Res.string.orders_returns_current_title.key to "Les retours restent actifs pendant 72 heures",
    Res.string.orders_returns_current_detail.key to "Les commandes livrees eligibles restent ici jusqu'a la fin du delai de retour.",
    Res.string.orders_back_to_orders.key to "Retour aux commandes",
    Res.string.orders_detail_title.key to "Detail de la commande",
    Res.string.orders_seller_pickup_code.key to "Code de retrait vendeur",
    Res.string.pass_access_title.key to "ACCES SEQUO",
    Res.string.pass_subscriber_detail.key to "Abonne Lome / 15% de reduction livraison",
    Res.string.pass_credit.key to "500 CFA de credit",
    Res.string.pass_addresses.key to "3 adresses a Lome",
    Res.string.notif_filter_today.key to "Auj.",
    Res.string.notif_filter_attention.key to "Attention",
    Res.string.notif_filter_promos.key to "Promos",
    Res.string.notif_filter_archived.key to "Archives",
    Res.string.notif_header_attention.key to "A traiter",
    Res.string.notif_inbox.key to "Inbox",
    Res.string.notif_unread.key to "non lus",
    Res.string.notif_need_attention.key to "a traiter",
    Res.string.notif_archived_lower.key to "archives",
    Res.string.notif_empty_detail.key to "Toutes vos notifications seront gardees ici pour consulter leur etat a tout moment.",
    Res.string.notif_empty_today.key to "Aucune notification",
    Res.string.notif_empty_attention.key to "Aucune urgence",
    Res.string.notif_empty_promos.key to "Aucune promo",
    Res.string.notif_empty_archived.key to "Rien d'archive",
    Res.string.notif_cancelled_suffix.key to "annulee",
    Res.string.notif_cancelled_detail.key to "L'offre du vendeur a ete refusee et retiree du paiement.",
    Res.string.notif_restore.key to "Restaurer",
    Res.string.notif_show.key to "Afficher",
    Res.string.notif_archive.key to "Archiver",
    Res.string.notif_pickup_code.key to "Code retrait",
    Res.string.notif_handoff_hint.key to "A montrer seulement lors de la remise.",
    Res.string.account_subscription_active.key to "Abonne",
    Res.string.account_subscription_detail.key to "-15% / 500 CFA credit",
    Res.string.account_saved_places.key to "Adresses",
    Res.string.account_home.key to "Maison",
    Res.string.account_family.key to "Famille",
    Res.string.account_office.key to "Bureau",
    Res.string.account_supported_payments.key to "Paiements",
    Res.string.account_no_cash.key to "sans cash",
    Res.string.account_primary.key to "Principal",
    Res.string.account_backup.key to "Secours",
    Res.string.account_tools.key to "Outils",
    Res.string.account_secure.key to "securise",
    Res.string.account_payments.key to "Paiements",
    Res.string.account_returns.key to "Retours",
    Res.string.account_delivery_credit.key to "Credit livr.",
    Res.string.account_subscription.key to "Abonnement",
    Res.string.account_active_15.key to "15% actif",
    Res.string.account_guest_title.key to "Invite",
    Res.string.account_guest_detail.key to "Creez un compte ou connectez-vous quand vous voulez enregistrer des paniers, commander, suivre la livraison et gerer les paiements.",
    Res.string.account_sign_in_create.key to "Connexion / compte",
    Res.string.account_customer.key to "Client Sequo",
    Res.string.account_no_email.key to "Aucun email",
    Res.string.account_provider.key to "Provider",
    Res.string.account_unknown.key to "inconnu",
    Res.string.account_sign_out.key to "Se deconnecter",
)

private val FrenchCatalogStrings = mapOf(
    "all" to "Tout",
    "catalog" to "Catalogue",
    "available" to "Disponible",
    "catalog synced" to "Catalogue synchronise",
    "standard delivery" to "Livraison standard",
    "negotiable" to "Negociable",
    "food" to "Repas",
    "grocery" to "Epicerie",
    "fashion" to "Mode",
    "electronics" to "Tech",
    "pharmacy" to "Pharmacie",
    "beauty" to "Beaute",
    "bargains" to "Deals",
    "hot meal" to "Chaud",
    "hot meals" to "Chaud",
    "meals" to "Repas",
    "meal" to "Repas",
    "fast food" to "Fast-food",
    "restaurant" to "Restaurant",
    "restaurants" to "Restaurants",
    "fresh food" to "Frais",
    "fresh" to "Frais",
    "daily" to "Quotidien",
    "market" to "Marche",
    "markets" to "Marches",
    "shops" to "Boutiques",
    "shop" to "Boutique",
    "store" to "Boutique",
    "stores" to "Boutiques",
    "baby care" to "Bebe",
    "soaps & cleaners" to "Savons et menage",
    "paper goods" to "Papier",
    "socks" to "Chaussettes",
    "football jerseys" to "Maillots",
    "basketball jerseys" to "Basket",
    "shoes" to "Chaussures",
    "t-shirts" to "T-shirts",
    "shirts" to "Chemises",
    "shorts" to "Shorts",
    "denim" to "Jean",
    "watches" to "Montres",
    "perfume" to "Parfum",
    "makeup" to "Maquillage",
    "phones" to "Telephones",
    "laptops" to "Ordinateurs",
    "auto parts" to "Auto",
    "seafood" to "Poisson",
    "meat" to "Viande",
    "pantry" to "Epicerie",
    "produce" to "Frais",
    "open" to "Ouvert",
    "closed" to "Ferme",
)
